### ISSUE TITLE
Pact language implementation compatibility suite

### ISSUE THREAD

**Issue by mefellows** [pactflow/roadmap#100]
**Problem**
Maintainers of a Pact client language currently lack a detailed implementation and ongoing maintenance guide. The Pact ecosystem and feature suite is also quite vast, and it can be hard to know when a client language is "done".

**Solution**
In consultation with the open source maintainer and contributor community, PactFlow will be building a set of guides, tutorials/workshops, test criteria and a reference language that demonstrates how to use the various SDKs to create a feature complete language.

Called **"Maintainer Experience"**, it is an accessible set of educational materials, and improvements to our core SDKs to simplify the experience for maintainers and community contributors contributing to the ecosystem.

The Test compatibility suite is a BDD acceptance testing suite (written in gherkin) that covers all of the Pact behaviour required to achieve full language support/parity. 

Each language would pull in the BDD suite and implement the scenarios they support. It’s a Test Compatibility Kit (TCK) type model. Initially, this would be added to the Pact JVM and Rust languages

**Comment by mefellows** [comment]
The compatibility suite is currently in progress here:
https://github.com/pact-foundation/pact-compatibility-suite/

**Comment by YOU54F** [comment]
Current examples

- [pact-rust](https://github.com/pact-foundation/pact-reference/tree/master/compatibility-suite)
- [pact-jvm](https://github.com/pact-foundation/pact-jvm/tree/master/compatibility-suite)
- [pact-php](https://github.com/pact-foundation/pact-php/tree/master/compatibility-suite)
- [pact-python](https://github.com/pact-foundation/pact-python/tree/master/tests/v3/compatibility_suite)
- [pact-ruby-ffi](https://github.com/YOU54F/pact-ruby-ffi/tree/main/compatibility-suite)
