### ISSUE TITLE
Contract Capture: common adapters

### ISSUE THREAD

**Issue by mefellows** [pactflow/roadmap#34]
To support #4 and accelerate the use of bi-directional contracts, we would like to create common `contract capture adapters` - tools that would take an existing mock or test, and convert into a pact file (sans matchers). 

We are currently thinking of the following, but are looking for feedback on tools to support initialy:

- [x] Cypress
- [x] MSW
- [x] Wiremock
- [x] RestAssured

**Comment by pogodins** [comment]
Hi,
I submitted a request for Playwright integration #77.
Could you please include it also in you implementation plan?
Playwright is a direct competitor of Cypress and is rapidly being adopted by teams.

**Comment by mefellows** [comment]
I'm going to close this item as we don't plan on adding any new integrations in the next couple of months, and we don't want this item itself living on the roadmap indefinitely.

Any other adaptors we decide to build will be prioritised and displayed on our roadmap board, and of course, we encourage anyone to build your own and share :)
