### ISSUE TITLE
Pactflow UI Bug with `?` tooltips

### ISSUE THREAD

**Issue by dabfleming** [pactflow/roadmap#43]
So if I mouse over the circled question marks as in the Edit Role admin screen, if I wait a few seconds a tooltip comes up describing the role. The first tooltip seems to come up slowly ~2 sec, and then when I mouse over other ?s subsequent tips come up much faster <0.5sec. The delay on the first tool tip displaying made me think that I had to click the ? to get the tip.. but after clicking the tool tip _never_ displays. Indeed if you wait until a tip displays and then click, the tip is dismissed?

Initially I was trying clicking and couldn't get any tips to display. I would suggest either having clicking immediately display the tip (and only hide on mouse-out) or at least not allowing clicking to dismiss the tip. It would also be nice to reduce the initial delay to be consistent with later tooltip display, if possible.

This was something that drove me nuts for a short time, so hoping to save some others the headache.

(Chrome (current ~94/95) on MacOS Catalina)

**Comment by bethesque** [comment]
Thanks for the feedback @dabfleming 

cc: @B3nnyL

**Comment by B3nnyL** [comment]
@dabfleming Thanks for your feedback, the issue should be resolved.
