### ISSUE TITLE
MSW Adapter

### ISSUE THREAD

**Issue by mefellows** [pactflow/roadmap#63]
MSW plugin to generate contracts from MSW stub configurations

**Comment by YOU54F** [comment]
- [X] Update msw-pact based on Juan Cruz's feedback. [PR](https://github.com/YOU54F/msw-pact/pull/27) 
- [X] Create initial pactflow [example consumer example ](https://github.com/pactflow/example-consumer-msw)
- [ ] Create example for worker (browser) based mode
- [ ] Header filter (exclusion/inclusion) - provider specific?
- [ ] Setup CI Pipeline for testing
- [ ] Setup CI Pipeline for publishing
- [ ] Transfer ownership of repo to pact-foundation
- [ ] Publish from npm pact-foundation org/scope

**Comment by YOU54F** [comment]
@mefellows 

- I've transferred https://github.com/YOU54F/msw-pact to https://github.com/pact-foundation/msw-pact
- I've created an msw-pact maintainers team in the foundation and added yourself, would you mind adding msw-pact to the list of repositories within the team https://github.com/orgs/pact-foundation/teams/msw-pact/repositories

There is a couple of tasks required to complete the `Publish from npm pact-foundation org/scope` task

- [ ] create pact-foundation scope token and add to environment under NPM_AUTOMATION_TOKEN
- [ ] change the deploy script to have `--access-public` as it will be published under pact-foundation scope
- [ ] change `package.json` to have `@pact-foundation` scope.

**Comment by YOU54F** [comment]
see https://github.com/pactflow/msw-pact/pull/36
