### ISSUE TITLE
Provider contract CLI Publishing Tool

### ISSUE THREAD

**Issue by mefellows** [pactflow/roadmap#68]
## Provider contract CLI Publishing Tool

> The ability to publish a provider contract (such as an OAS) and verification results to Pactflow via a CLI.

Publish provider contract to Pactflow

###  
1. Add Pactflow Command to CLI sources 
    1. [x] Gem [pact_broker-client](https://github.com/pact-foundation/pact_broker-client)
    1. [x] CLI [pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone)
    1. [x] Docker [pact-ruby-cli](https://github.com/pact-foundation/pact-ruby-cli)
    1. [x] GitHub Action [github-actions-pact-publish-provider-contract](https://github.com/pactflow/github-actions-pact-publish-provider-contract)
1. Add examples
    1. [x] Docs [docs.pactflow.io](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas#publishing-the-provider-contract--results-to-pactflow)
    1. [x] Gem [pact_broker-client](https://github.com/pact-foundation/pact_broker-client#provider-contracts)
    1. [x] CLI [pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone)
    1. [x] Docker [pact-ruby-cli](https://github.com/pact-foundation/pact-ruby-cli)
    1. [x] GitHub Action [github-actions-pact-publish-provider-contract](https://github.com/pactflow/github-actions-pact-publish-provider-contract)
    1. [x] Demo [postman](https://github.com/pactflow/example-bi-directional-provider-postman)
    1. [x] Demo [dredd](https://github.com/pactflow/example-bi-directional-provider-dredd)
    1. [x] Demo [restassured](https://github.com/pactflow/example-bi-directional-provider-restassured)
    1. [x] Demo [dotnet](https://github.com/pactflow/example-bi-directional-provider-dotnet)
    1. [x] Katacoda https://github.com/pactflow/katacoda-workshops/blob/master/pactflow-bi-directional-contracts-intro/step4.md
    1. [x] BDCT Workshops
      1. [x] Workshop https://docs.pactflow.io/docs/workshops/bi-directional/pre_requisites
      3. [x] Quick start guide https://docs.pactflow.io/docs/workshops/quick_starts/bdc
5. Improve examples
      1. [x] Remove env var for PACTFLOW FEATURE
      1. [x] Use `PACT_CLI_DOCKER_VERSION` env var or fallback to `latest`
      1. GitHub Actions
          1. [x] Allow triggering of build with `PACT_CLI_DOCKER_VERSION`
          1. [x] GH Matrix - Separate Workflow, use composite consumer name
            1. [x] build to test Different OS's (mac/linux/windows)
            1. [x] build to test Different Docker CLI versions
            1. [x] build to test Different ways of publishing
               1. [x] Gem [pact_broker-client](https://github.com/pact-foundation/pact_broker-client)
               1. [x] CLI [pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone)
               1. [x] Docker [pact-ruby-cli](https://github.com/pact-foundation/pact-ruby-cli)
               1. [x] GitHub Action [github-actions-pact-publish-provider-contract](https://github.com/pactflow/github-actions-pact-publish-provider-contract)
      1. Trigger example build on update of CLI tools
         1. [ ] Gem [pact_broker-client](https://github.com/pact-foundation/pact_broker-client)
         1. [ ] CLI [pact-ruby-standalone](https://github.com/pact-foundation/pact-ruby-standalone)
         1. [ ] Docker [pact-ruby-cli](https://github.com/pact-foundation/pact-ruby-cli)
         1. [ ] GitHub Action [github-actions-pact-publish-provider-contract](https://github.com/pactflow/github-actions-pact-publish-provider-contract)

**Comment by YOU54F** [comment]
See https://ncorti.com/blog/howto-github-actions-build-matrix for ideas for testing upcoming work

> A great use case for build matrix is the setup of shadow CI jobs 👻.
>
> A shadow CI job is a job that tests your project against an unreleased/unstable version of a dependency of your project. This helps you spot integration problems and regressions early on.
> 
> Generally, you want to treat a failure in a shadow job like a warning and don’t fail your whole workflow. This because you just want to get notified of a potential failure in the future, once a dependency becomes stable.
> 
> With such a setup, you could reach out to the library maintainer and notify them about unexpected problems or breaking changes.

**Comment by YOU54F** [comment]
Now delivered 🚀 

[Website docs](https://docs.pactflow.io/docs/bi-directional-contract-testing/contracts/oas#publishing-the-provider-contract--results-to-pactflow)

1. [Docker](https://hub.docker.com/r/pactfoundation/pact-cli)
1. [Pact Standalone CLI](https://github.com/pact-foundation/pact-ruby-standalone/releases)
1. [Pact Broker Client (Ruby)](https://github.com/pact-foundation/pact_broker-client#provider-contracts)
1. [Github Actions](https://github.com/pactflow/actions/tree/main/publish-provider-contract)
