### ISSUE TITLE
Delete integration removes all pacts (bug?)

### ISSUE THREAD

**Issue by AudriusDai** [pactflow/roadmap#79]
# Problem statement
I have OAS pact for service A. Then I have pact files for service B and C. The service B & C are referencing to service A. Which means there are two integrations: B -> A, C -> A. When I choose to delete an integration between services B -> A, I get the disclaimer with information: (check images below)
![image](https://user-images.githubusercontent.com/34154358/184130102-32648f5d-24c4-48a3-b52e-1fa472b752b9.png)
![image](https://user-images.githubusercontent.com/34154358/184129921-86e2e1e8-c015-4730-b506-1c2434f737aa.png)
With the information text "..that are not associated with other integrations.." it suggests me that none of other integration are going to be touched. When I proceed by clicking on "DELETE" button, it removes data from other integrations (i.e. C -> A) also. And that was not expected.

Could you verify that this is a bug? If so, when would you expect to fix that?

**Comment by bethesque** [comment]
Can you send an email to support@pactflow.io with the details of your Pactflow account (ie. if onprem, which version, if SaaS, which tenant) how to reproduce the issue, which pacts were deleted etc.

**Comment by bethesque** [comment]
@AudriusDai this has been fixed.
